os:
  - linux
services:
  - docker
language: node_js
cache:
  directories:
    - $HOME/.m2
node_js:
  - "4.2.1"
jdk:
  - oraclejdk8
before_install:
  - npm install -g bower
  - npm install -g grunt-cli
  - git config user.name "$GIT_NAME"
  - git config user.email "$GIT_EMAIL"
install:
  - npm install
  - bower install
script:
  - mvn test install -Pprod
  - grunt test
env:
  global:
  - GIT_NAME="James Dunnam"
  - GIT_EMAIL=jamesd1184@gmail.com
  - MAVEN_OPTS="-Xms2048m -Xmx=2048m"
